### ISSUE TITLE
Any chance of support for duplications and inversions?

### ISSUE THREAD

**Issue by oneillkza** [smehringer/SViper#15]
Hi!

Is there any chance you'll support duplications and inversions in SViper any time soon? Both are fairly common in a clinical cohort I'm looking at. In theory they should be fairly simple, as it's really just a case of refining a breakpoint.

Alternately, would it be possible to add functionality to manually specify the variant reads? Sniffles provides a list of breakpoint reads in its output, which I could pass down to SViper for polishing.

Thanks!

**Comment by smehringer** [comment]
Hi @oneillkza,

thanks for your interest in SViper!

> Is there any chance you'll support duplications and inversions in SViper any time soon? Both are fairly common in a clinical cohort I'm looking at. In theory they should be fairly simple, as it's really just a case of refining a breakpoint.

I don't know how much time I will have to work on this. I'll keep you posted.

> Alternately, would it be possible to add functionality to manually specify the variant reads? Sniffles provides a list of breakpoint reads in its output, which I could pass down to SViper for polishing.

This feature would be easier. How does sniffles pass this information on?

**Comment by oneillkza** [comment]
@smehringer thanks -- that would be very helpful!

Sniffles provides the read names in the RNAMES field in the vcf, which can then be filtered out of the bam file. Here's an example line from a vcf:

```
1       2614393 59_5    N       <DEL>   .       PASS    IMPRECISE;SVMETHOD=Snifflesv1.0.10;CHR2=1;END=2614448;STD_quant_start=18.212633;STD_quant_stop=13.202273;Kurtosis_quant_start=0.606836;Kurtosis_quant_stop=0.360472;SVTYPE=DEL;RNAMES=1c818ec5-2b0e-42b9-94cb-0a74c9f0a92a,2b306430-3f4a-4115-88de-bafb7bcb3630,2f7cec9d-97a8-4b4b-92b2-f7805ce498ab,449825de-0355-4154-aac0-d215f969d8c0,693cb624-a5c6-4afe-a992-da148b28344d,89d95b03-3e3e-4643-854f-d6136aaa015d,8f16a4be-3d78-4dfd-9793-94ab2881e595,a22ca667-5297-4fbf-90e4-9d6a2f95b9cd,a9896f60-bd37-4ebf-8ca7-9eb6afa32230,b0a6426e-0d01-47e0-b3dd-d5e8adcf5348,cd9c3198-c840-4056-8bad-be678ebd26d3,d89028fb-ace9-46b8-975f-ab339db1d940,dc07ebb4-c53c-4958-8edd-d26d2ea0c905,e29d2a10-d3d7-4f6b-a88e-b62ba846ea71,f2b1af1e-e3c4-477e-89f8-49d4c5ac3d3d,fec31226-62ac-42c9-ae95-276206cd09b9;SUPTYPE=AL;SVLEN=-55;STRANDS=+-;RE=16;REF_strand=4,1;AF=0.761905  GT:DR:DV        0/1:5:16
```

Note: Sniffles doesn't do this by default, but it can be turned out using the -n parameter.

**Comment by smehringer** [comment]
Hi @oneillkza 

I am very sorry for not working on this and I guess it's been way too long to be of interest any longer. If you are still interested in this feature please reopen the issue!
