### ISSUE TITLE
[README, MINOR, FIX, PLEASE, INTERNAL] Incorrect git link 

### ISSUE THREAD

**Issue by hannespetur** [smehringer/SViper#2]
Dear Mehringer,

Thank you for your great contribution. I noticed a minor issue in the readme file, the git link is incorrect in the installation instructions for cloning the repository. The command for cloning should be

```
~$ git clone git@github.com:smehringer/SViper.git
```

All the best,
Mr. Eggertsson

**Comment by smehringer** [comment]
Thank you very much for catching this! I'll fix it right away.
Best,
Svenja (:smirk:)

**Comment by smehringer** [comment]
Fixed in commit #33c919c

**Comment by hannespetur** [comment]
Thank you very much Svenja for a quick response and a good 'good first issue' fix. Keep up your excellent work.

All the best,
Hannes
