### ISSUE TITLE
Segmentation fault for few SVs

### ISSUE THREAD

**Issue by Han-Cao** [smehringer/SViper#23]
Hi,

I am working on PacBio data and want to use sviper in my pipeline. I used the latest version and successfully corrected most of my SVs. However, I ran into segmentation fault for very few SVs. No additional error information was raised and sviper just stop without output vcf.

Please see the following link for a reproducible example and log file: https://www.dropbox.com/s/mhntmdae9px243g/sviper.zip?dl=0

The code I used is:
sviper -s short_read.bam -l long_read.bam -r hg38.fa -c test_input.vcf -o test_output -t 1

Thanks,
Han

**Comment by smehringer** [comment]
Hi @Han-Cao,

thanks for your interest in SViper. I'll try to have a look at your SVs the next week. Thanks for providing the data!

Best,
Svenja

**Comment by smehringer** [comment]
Hi @Han-Cao ,

could you check if https://github.com/smehringer/SViper/pull/24 fixes the issue also on your side? It does for me.

**Comment by Han-Cao** [comment]
Hi @smehringer,

It also works for me. Thanks for your work!

Best,
Han
