### ISSUE TITLE
Command line parameters for FAIL5 thresholds

### ISSUE THREAD

**Issue by eldariont** [smehringer/SViper#6]
Hi,

currently the thresholds for rejecting a polished variant because of its dissimilarity to the original variant (FAIL5) are hardcoded here: https://github.com/smehringer/SViper/blob/master/include/variant.h#L8

Would it be possible to add user parameters for DEV_SIZE and DEV_POS?

Thank you
David

**Comment by smehringer** [comment]
Hey @eldariont,

can you checkout branch `feature_deviation_user_parameter` and try out the user parameters for deviation size and pos? I don't have time to check if the output is as expected for the same input so maybe you can check.

(Check the advanced help page with `-hh`)

Best,
Svenja

**Comment by smehringer** [comment]
@eldariont Feel free to reopen this if it is not fixed for you.
